DROP table USER2;
DROP table VIDEO2;
DROP table VIDEO_HISTORY2;
DROP table KEYWORD2;
DROP table BOARD2;
DROP table BOARD_POST2;
DROP table COMMENT2;
DROP table MEMBERSHIP2;
DROP table CALENDAR2;


CREATE TABLE USER2 (
	user_id			varchar2(100)		NOT NULL,
	user_pw			varchar2(20)		NOT NULL,
	membership_name	varchar2(20)		NOT NULL,
	user_name		varchar2(100)		NOT NULL,
	age				number				NOT NULL,
	gender			varchar2(100)		NOT NULL
);

CREATE TABLE VIDEO2 (
	video_id	number				NOT NULL,
	user_id		varchar2(100)		NOT NULL,
	file_name	varchar2(100)		NOT NULL,
	play_time	number				NOT NULL,
	upload_time	date				NOT NULL,
	Field		VARCHAR2(255)		NULL
);

CREATE TABLE VIDEO_HISTORY2 (
	history_id	number				NOT NULL,
	video_id	number				NOT NULL,
	user_id		varchar2(100)		NOT NULL,
	start_time	number				NOT NULL,
	end_time	number				NOT NULL,
	talk		varchar2(300)		NOT NULL,
	bookmark	char(1)				NOT NULL
);

CREATE TABLE KEYWORD2 (
	keyword_id	number				NOT NULL,
	video_id	number				NOT NULL,
	user_id		varchar2(100)		NOT NULL,
	keword		varchar2(20)		NOT NULL,
	count		number				NOT NULL
);

CREATE TABLE BOARD2 (
	board_id	number				NOT NULL,
	board_name	varchar2(20)		NULL
);

CREATE TABLE BOARD_POST2 (
	post_id			number				NOT NULL,
	user_id			varchar2(100)		NOT NULL,
	board_id		number				NOT NULL,
	post_time		date				NOT NULL,
	post_title		varchar2(50)		NOT NULL,
	post_contents	varchar2(500)		NOT NULL
);

CREATE TABLE COMMENT2 (
	comment_id			number			NOT NULL,
	post_id				number			NOT NULL,
	user_id				varchar2(100)	NOT NULL,
	comment1			varchar2(300)	NOT NULL,
	comment_parent_id	number			NULL
);

CREATE TABLE MEMBERSHIP2 (
	membership_id		number			NOT NULL,
	membership_name		varchar2(20)	NOT NULL
);

CREATE TABLE CALENDAR2 (
	cal_id		number			NOT NULL,
	user_id		varchar(100)	NOT NULL,
	cal_date	date			NOT NULL,
	cal_todo1	varchar(200)	NULL,
	cal_todo2	varchar(200)	NULL,
	cal_todo3	varchar(200)	NULL
);

ALTER TABLE USER2 ADD CONSTRAINT PK_USER PRIMARY KEY (user_id);
ALTER TABLE VIDEO2 ADD CONSTRAINT PK_VIDEO PRIMARY KEY (video_id);
ALTER TABLE VIDEO_HISTORY2 ADD CONSTRAINT PK_VIDEO_HISTORY1 PRIMARY KEY (history_id);
ALTER TABLE KEYWORD2 ADD CONSTRAINT PK_KEYWORD1 PRIMARY KEY (keyword_id);
ALTER TABLE BOARD2 ADD CONSTRAINT PK_BOARD PRIMARY KEY (board_id);
ALTER TABLE BOARD_POST2 ADD CONSTRAINT PK_BOARD_POST1 PRIMARY KEY (post_id);
ALTER TABLE COMMENT2 ADD CONSTRAINT PK_COMMENT PRIMARY KEY (comment_id);
ALTER TABLE MEMBERSHIP2 ADD CONSTRAINT PK_MEMBERSHIP PRIMARY KEY (membership_id);
ALTER TABLE CALENDAR2 ADD CONSTRAINT PK_CALENDAR PRIMARY KEY (cal_id);

	
ALTER TABLE USER2 ADD CONSTRAINT FK_USER_MEMBERSHIP FOREIGN KEY (membership_id) REFERENCES MEMBERSHIP2 (membership_id);

ALTER TABLE VIDEO2 ADD CONSTRAINT FK_USER_TO_VIDEO FOREIGN KEY (user_id) REFERENCES USER2(user_id);

ALTER TABLE VIDEO_HISTORY2 ADD CONSTRAINT FK_VIDEO_TO_VIDEO_HISTORY_1 FOREIGN KEY (video_id) REFERENCES VIDEO2(video_id);

ALTER TABLE VIDEO_HISTORY2 ADD CONSTRAINT FK_VIDEO_TO_VIDEO_HISTORY_2 FOREIGN KEY (user_id) REFERENCES USER2 (user_id);

ALTER TABLE KEYWORD2 ADD CONSTRAINT FK_VIDEO_TO_KEYWORD_1 FOREIGN KEY (video_id) REFERENCES VIDEO2 (video_id);

ALTER TABLE KEYWORD2 ADD CONSTRAINT FK_VIDEO_TO_KEYWORD_2 FOREIGN KEY (user_id) REFERENCES USER2 (user_id);

ALTER TABLE BOARD_POST2 ADD CONSTRAINT FK_USER_TO_BOARD_POST_1 FOREIGN KEY (user_id) REFERENCES USER2 (user_id);

ALTER TABLE BOARD_POST2 ADD CONSTRAINT FK_BOARD_TO_BOARD_POST_1 FOREIGN KEY (board_id) REFERENCES BOARD2 (board_id);

ALTER TABLE COMMENT2 ADD CONSTRAINT FK_BOARD_POST_TO_COMMENT_1 FOREIGN KEY (post_id) REFERENCES BOARD_POST2 (post_id);

ALTER TABLE COMMENT2 ADD CONSTRAINT FK_BOARD_POST_TO_COMMENT_2 FOREIGN KEY (user_id) REFERENCES USER2 (user_id);

ALTER TABLE CALENDAR2 ADD CONSTRAINT FK_USER_TO_CALENDAR FOREIGN KEY (user_id) REFERENCES USER2 (user_id);
